### PR TITLE
Port small fixes from Melodic

### PR DESCRIPTION
**Pull request by artivis**
Porting small fixes from ROS 1 (all at once):
- https://github.com/ros/pluginlib/pull/158
- https://github.com/ros/pluginlib/pull/159
- https://github.com/ros/pluginlib/pull/163

After @nuclearsandwich [request](https://github.com/ros/pluginlib/pull/163#issuecomment-586524905).

### CODE REVIEW

**Comment by artivis** [comment]
@nuclearsandwich Writing tests to cover those specific fixes feels flaky. Those fixes do not throw or the error is caught and redirected through the `LOG_ERROR` macro. Furthermore the interesting bits of `ClassLoader` API are `private` which doesn't help either.

Edit: I guess one could search for the error message in stderr (e.g.`::testing::internal::GetCapturedStderr()`) ...

**Comment by kyrofa** [comment]
Hey @nuclearsandwich, does this one look okay?

**Comment by clalancette** [comment]
I've rebased this onto the latest.  The code looks good to me, so I'll approve and run CI on it.

**Review by clalancette — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12851/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7806/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10562/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12794/)

**Pull request merged**
