### PR TITLE
Add std::unique_ptr API

### PR DESCRIPTION
**Pull request by de-vri-es**
This follows https://github.com/ros/class_loader/pull/38 and adds the API to `pluinglib` as well. That means it requires `indigo-devel` from `class_loader` to build, which is probably not available for the automated tests. I'm not sure what the best solution is for that. It would be nice to release this API addition together with `class_loader`.

Points to note for the review:
- I put the unit test in a separate file. I was tempted to put them in the same file with the other tests, but that would have required compiling those tests with C++11 support as well. I figured it was best not to do that, to make sure no hard requirements on C++11 features sneak in where they shouldn't.
- I switched manual try/catch statements in the unit test with `ASSERT_THROW` for readability. `ASSERT_THROW` checks the exception type, so old behaviour of the test is maintained.
- I also cleaned up some white space errors and long unwrapped comments. I can undo those if desired.

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
Thanks for the follow up PR, the change looks good for me.
I'll test them locally on the different distros and release them together to run the tests all at once on the buildfarm.
It's ok to have the cleanup (whitespace/wrapping) commit in the same PR.
Thanks for replicating the c++11 check for compiling the tests.
Will comment here once tested locally

**Review by davetcoleman — APPROVED** [review]
I skimmed the changes

**Comment by mikaelarguedas** [comment]
tested locally on both kinetic and indigo without problem

**Review by mikaelarguedas — APPROVED** [review]

**Comment by de-vri-es** [comment]
Thanks for the quick review and merge :)

**Comment by mikaelarguedas** [comment]
Released on kinetic and will release on earlier distros once we're sure that no unexpected behaviour emerges

**Comment by v4hn** [comment]
It would be great to have this available in indigo too! So +1 to backport this change to indigo and jade

**Pull request merged**
