### PR TITLE
move pluginlib in its own folder (port 83 to ros2 branch)

### PR DESCRIPTION
**Pull request by mikaelarguedas**

### CODE REVIEW

**Comment by mikaelarguedas** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3790/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/929/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3126/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3876/)

**Review by wjwwood — APPROVED** [review]
+1 for merge

I guess it would have been nice to rebase the ros2 branch instead, but now that we’ve made a release from it we probably shouldn’t do anything that doesn’t fast-forward. Later might have to make a commit to bring it back in step completely with melodic development and then readd the ros2 specific stuff. Oh well we can figure that out later.

**Comment by mikaelarguedas** [comment]
Ok I updated and manually ported the parts of the PRs recently merged in melodic:
#83, #84, #88 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3808/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/946/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3147/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3895/)

**Comment by mikaelarguedas** [comment]
Note: I haven't fixed one set of uncrustify errors as I'm not convinced uncrustify does the right thing here:
```
--- pluginlib/include/pluginlib/impl/filesystem_helper.hpp
+++ pluginlib/include/pluginlib/impl/filesystem_helper.hpp.uncrustify
@@ -39 +39 @@
-#if __has_include(<filesystem>)
+#if __has_include(< filesystem >)
@@ -51 +51 @@
-#elif __has_include(<experimental/filesystem>)
+#elif __has_include(< experimental / filesystem >)
```

**Pull request merged**
