### PR TITLE
Fix dev build dep on TinyXML2

### PR DESCRIPTION
**Pull request by mjcarroll**
Tests weren't properly depending on tinyxml2_vendor.

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
Was this causing specific errors somewhere?

**Comment by mjcarroll** [comment]
Yes, on Windows, if I recall correctly, if you didn't depend on tinyxml2_vendor, then TinyXML2 wouldn't be found.

**Comment by nuclearsandwich** [comment]
@mjcarroll it seems like we haven't actually needed this change for our Windows builds nor have I seen any user reports about it.

At first I was hoping to avoid explicit dependencies on our vendor packages but without this patch we're basically just "getting lucky" with TinyXML2 being available prior to finding tinyxml2_vendor. So let's get CI sorted and get this merged.

**Comment by nuclearsandwich** [comment]
>  So let's get CI sorted and get this merged.

We dropped Travis from the ROS 2 branch in #142. The Travis CI failure is invalid and can be ignored.

**Comment by mjcarroll** [comment]
Do you want me to rebase?

**Comment by nuclearsandwich** [comment]
> Do you want me to rebase?

The PR will get squash-merged and there aren't any current conflicts. As long as we use the branch feature on ci.ros2.org this branch will be merged into the ros2 one for CI. But it can't hurt.

**Pull request closed without merging**
