### PR TITLE
Use rcpputils for the filesystem implementation.

### LINKED ISSUE #168: Errors building with XCode 11 on Mojave
Installing XCode from the app store currently brings XCode 11. However there is a long list of errors when building pluginlib with it on macOS Mojave. It's unclear from the error text whether upgrading to macOS 10.15 before using XCode 11 will be sufficient to resolve the issue and I don't have any Catalina machines to try on.

stderr log from a test build: https://gist.github.com/nuclearsandwich/307e2f33edf5ba4db2188443bcf39987

### PR DESCRIPTION
**Pull request by clalancette**
This gets rid of a whole bunch of custom logic and duplicated
code around filesystem manipulation.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

If I understand the situation correctly, this should supersede #209, #185, and #184, and may fix #168.

@Karsten1987, @rotu, @jpardeiro FYI.

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12969/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7919/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10690/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12919/)

**Comment by clalancette** [comment]
All right, this has to wait to go in until ros2/rcpputils#112 is merged.  After that, it should pass tests.

**Review by mjcarroll — APPROVED** [review]
Looks good to me with green CI.

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13082/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8024/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10802/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13062/)

**Comment by clalancette** [comment]
Now that we've merged https://github.com/ros2/rcpputils/pull/118, this should be a lot easier.  Let's try CI again:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13411/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8331/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11136/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13470/)

**Review by Karsten1987 — APPROVED** [review]

**Comment by clalancette** [comment]
The one failing test on macOS often fails on the nightlies: https://ci.ros2.org/view/nightly/job/nightly_osx_repeated/2218/#showFailuresLink .  So I'm going to go ahead and merge this.

**Pull request merged**
