### PR TITLE
Ros2 reorganize tests

### PR DESCRIPTION
**Pull request by mjcarroll**
This will replace Mikael's rework in #94.

This has the addition of a `test_pluginlib_fixture` package to exercise the full extent of `pluginlib`.

### CODE REVIEW

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5357/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2084/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4447/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5317/)

**Comment by mjcarroll** [comment]
Once more, with properly disabling boost: 

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5358/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2085/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4448/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5318/)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5359/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2086/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4449/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5319/)

**Comment by mjcarroll** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5360/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2087/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4450/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5320/)

**Comment by mjcarroll** [comment]
With Windows issues cleaned up:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5363/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2090/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4453/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5323/)

**Comment by mjcarroll** [comment]
Full build to make sure that I didn't hose up any downstream consumers:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/5364/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/2091/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/4454/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/5324/)

**Review by nuclearsandwich — APPROVED** [review]
lgtm pending CI. Thanks for keeping the ball rolling @mjcarroll

**Comment by mjcarroll** [comment]
There were a couple unrelated failures, but I believe that they were resolved with https://github.com/ros2/system_tests/pull/302#issuecomment-433479955, which ran 4 hours ago (compared to my last run 6 hours ago).

**Pull request merged**
