### PR TITLE
Move LibraryLoadExceptions down a level for more accurate error msgs

### PR DESCRIPTION
**Pull request by DLu**
The error message saying "maybe it has the wrong name or maybe the library doesn't exist" has always bugged me.

### CODE REVIEW

**Comment by DLu** [comment]
Thoughts @hidmic ?

**Review by hidmic — APPROVED** [review]
LGTM once CI goes green.

CI up to `pluginlib`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/15724/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/10406/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/13389/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/15968/)

**Comment by hidmic** [comment]
@DLu would you mind signing off your commit?

**Comment by DLu** [comment]
Rebased and signed!

**Comment by DLu** [comment]
@Mergifyio backport foxy galactic

**Comment by DLu** [comment]
@jacobperron Am I not wizard enough to get the bot to listen to me? Or is it per-repo magic? :mage:

**Comment by jacobperron** [comment]
> @jacobperron Am I not wizard enough to get the bot to listen to me? Or is it per-repo magic? mage

Bot might only be enabled for the `ros2` org; not sure.

**Comment by DLu** [comment]
@hidmic Could we merge the backports of this PR? 
 * #228 
 * #229 
 * #230 
 * #231 

The CI appears to pass for all.

**Comment by hidmic** [comment]
@DLu I'll take a look. Thanks for the bump.

**Comment by hidmic** [comment]
@DLu this patch effectively changes the way `ClassLoader::getClassLibraryPath()` fails, which can break downstream code. That's fine for Rolling, not so much for stable, LTS distros. I'll check with ROS Bosses, see what they think.

**Comment by jacobperron** [comment]
I agree with @hidmic, the change doesn't seem worth the potential fallout of breaking users.

**Pull request merged**
