### PR TITLE
Fix compilation in Mac OS X

### PR DESCRIPTION
**Pull request by jpardeiro**
Tested in Mac OS X 10.15.4

### CODE REVIEW

**Comment by nuclearsandwich** [comment]
@jpardeiro #183 made a similar change on master which I think should cover this case as well as Clang on Linux, even though the Clang version on Eloquent's supported Linux platforms won't have this deprecation message yet. I think backporting that change would make more sense than creating this parallel one. Would you be willing to cherry pick that PR against Eloquent locally and test that it works for you?

**Comment by jpardeiro** [comment]
@nuclearsandwich it definitely makes more sense :). I will test it and go back to you as soon as I have the results.

**Comment by jpardeiro** [comment]
@nuclearsandwich I cherry picked the PR you mentioned and recompiled my eloquent distro workspace without any issue. Should I just decline this PR? Or rebase it with the integration of the changes from #183 ?

**Comment by nuclearsandwich** [comment]
@jpardeiro if you want to close this and open a PR with the cherry-picked commit as an Eloquent backport that would be very much appreciated.

**Comment by jpardeiro** [comment]
@nuclearsandwich I rebased the branch so now it is only the cherry-pick merge commit. If I should decline this and create a new PR, it is not a problem.

**Comment by jpardeiro** [comment]
@nuclearsandwich I just realised this PR has been opened during quite some time. Am I missing something? :)

**Comment by nuclearsandwich** [comment]
> I just realised this PR has been opened during quite some time. Am I missing something?

No I've just been starved for maintenance time. I've put this issue on the Eloquent patch release board and here's CI for it.

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12867/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7822/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10583/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12810/)

FYI @mjcarroll

**Pull request merged**
